name: Delete Stack on PR Close

on:
  pull_request:
    types:
      - closed

jobs:
  delete-stack:
    uses: ./.github/workflows/delete-stack-template.yaml
    with:
      stack-name: debug-env-${{ github.event.number }}
    secrets:
      AWS_ACCOUNT_NAME: ${{ secrets.AWS_ACCOUNT_NAME }}
      AWS_GITHUB_OIDC_ROLE_NAME: ${{ secrets.AWS_GITHUB_OIDC_ROLE_NAME }}
