name: Deploy to staging environment for PR

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  delete_stack:
    if: |-
      (github.event.pull_request.action != 'opened' ||
      github.event.pull_request.action != 'reopened')
      && contains(github.event.pull_request.labels.*.name, 'with_delete')
    uses: ./.github/workflows/delete-stack-template.yaml
    with:
      stack-name: debug-env-${{ github.event.pull_request.number }}
    secrets:
      AWS_ACCOUNT_NAME: ${{ secrets.AWS_ACCOUNT_NAME }}
      AWS_GITHUB_OIDC_ROLE_NAME: ${{ secrets.AWS_GITHUB_OIDC_ROLE_NAME }}
  deploy:
    if: ${{ always() }}
    needs: [delete_stack]
    uses: ./.github/workflows/deploy_job_template.yaml
    with:
      pr-number: ${{ github.event.pull_request.number }}
      stack-name: debug-env-${{ github.event.pull_request.number }}
      s3-dir: PR-${{ github.event.pull_request.number }}
    secrets:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCOUNT_NAME: ${{ secrets.AWS_ACCOUNT_NAME }}
      AWS_GITHUB_OIDC_ROLE_NAME: ${{ secrets.AWS_GITHUB_OIDC_ROLE_NAME }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
