name: Deploy AWS on dev branch

on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy_job_template.yaml
    with:
      pr-number: dev
      stack-name: dev
      s3-dir: dev