name: Deploy AWS CloudFormation
on:
  workflow_call:
    inputs:
      pr-number:
        description: 'Pull Request Number'
        required: true
        type: string
      stack-name:
        description: 'Stack Name'
        required: true
        type: string
      s3-dir:
        description: 'S3 Directory'
        required: true
        type: string
    secrets:
      AWS_S3_BUCKET:
        description: 'AWS S3 Bucket'
        required: true
      AWS_ACCOUNT_NAME:
        description: 'AWS Account Name'
        required: true
      AWS_GITHUB_OIDC_ROLE_NAME:
        description: 'AWS GitHub OIDC Role Name'
        required: true
      OPENAI_API_KEY:
        description: 'OpenAI API Key'
        required: true
      SLACK_WEBHOOK:
        description: 'Slack Webhook URL'
        required: false

env:
  AWS_REGION: 'ap-northeast-1'
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  AWS_ACCOUNT_NAME: ${{ secrets.AWS_ACCOUNT_NAME }}
  ROLE_TO_ASSUME: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NAME }}:role/${{ secrets.AWS_GITHUB_OIDC_ROLE_NAME }}
  OPENAPI_FILE: openapi.yaml
  PR_NUMBER: ${{ inputs.pr-number }}
  STACK_NAME: ${{ inputs.stack-name }}
  S3_DIR: ${{ inputs.s3-dir }}
  SLACK_USERNAME: DeployBot
  SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      checks: read
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup aws-sam
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          audience: sts.amazonaws.com

      - run: aws sts get-caller-identity

      - name: Upload to Amazon S3
        run: |-
          aws s3 cp --region ${AWS_REGION} ${OPENAPI_FILE} s3://${AWS_S3_BUCKET}/${S3_DIR}/${OPENAPI_FILE}
          aws s3api put-object-tagging --region ${AWS_REGION} --bucket ${AWS_S3_BUCKET} --key ${S3_DIR}/${OPENAPI_FILE} --tagging "TagSet=[{Key=public,Value=yes}]"

      - name: Build and Deploy Cloud Formation stacks
        id: deploy_step
        run: |
          sam build
          sam deploy --template-file .aws-sam/build/template.yaml --stack-name ${STACK_NAME} --capabilities CAPABILITY_NAMED_IAM --s3-bucket ${AWS_S3_BUCKET} --parameter-overrides OpenApiFile=${OPENAPI_FILE} S3Dir=${S3_DIR} S3Bucket=${AWS_S3_BUCKET} PrNumber=${PR_NUMBER} OpenAiApiKey=${{ secrets.OPENAI_API_KEY }} --no-fail-on-empty-changeset
          deployed_url=$(aws cloudformation describe-stacks --stack-name ${STACK_NAME} --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" --output text)
          echo "deployed_url=$deployed_url" >> $GITHUB_OUTPUT

      - name: Notify Slack to Deploy Success
        if: success() && env.SLACK_WEBHOOK != ''
        uses: rtCamp/action-slack-notify@v2.2.1
        env:
          SLACK_WEBHOOK: ${{ env.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: ${{ env.SLACK_ICON }}
          SLACK_USERNAME: ${{ env.SLACK_USERNAME }}
          SLACK_TITLE: "#${{ env.PR_NUMBER }} デプロイ成功!"
          SLACK_MESSAGE: "${{ steps.deploy_step.outputs.deployed_url }}"
          SLACK_FOOTER: ${{ github.event.pull_request.html_url }}

      - name: Notify Slack to Deploy Failure
        if: failure() && env.SLACK_WEBHOOK != ''
        uses: rtCamp/action-slack-notify@v2.2.1
        env:
          SLACK_WEBHOOK: ${{ env.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: ${{ env.SLACK_ICON }}
          SLACK_USERNAME: ${{ env.SLACK_USERNAME }}
          SLACK_TITLE: "#${{ env.PR_NUMBER }} デプロイ失敗!"
          SLACK_FOOTER: ${{ github.event.pull_request.html_url }}

      - name: Comment on PR
        if: success() && github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |-
            Deploy Success!!
            Deploy URL! ${{ steps.deploy_step.outputs.deployed_url }}
          comment_tag: 'deploy-success'
