name: Deploy AWS on dev branch

on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy_job_template.yaml
    with:
      pr-number: dev
      stack-name: dev
      s3-dir: dev
    secrets:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCOUNT_NAME: ${{ secrets.AWS_ACCOUNT_NAME }}
      AWS_GITHUB_OIDC_ROLE_NAME: ${{ secrets.AWS_GITHUB_OIDC_ROLE_NAME }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}