name: Lint python
on:
  pull_request:
    paths:
      - 'app/**.py'
      - 'layer/**.py'

jobs:
  lint:
    name: lint python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: '.'
      - name: Check import order using isort
        uses: isort/isort-action@v1
        id: action_isort
        with:
          isort_args: '. --profile=black'
      - name: Annotate diff changes using reviewdog
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: black & isort
