name: Lint python
on:
  pull_request:
    paths:
      - 'app/**.py'
      - 'layer/**.py'

jobs:
  black-isort-lint:
    name: Black and isort lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: '.'
      - name: Check import order using isort
        uses: isort/isort-action@v1
        id: action_isort
        with:
          configuration: '--profile=black'
      - name: Annotate diff changes using reviewdog
        uses: reviewdog/action-suggester@v1
  flake8-lint:
    runs-on: ubuntu-latest
    name: flake8 Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install pyproject-flake8
        run: pip install pyproject-flake8
      - name: flake8 Lint
        uses: reviewdog/action-flake8@v3
        with:
          reporter: github-pr-review
