name: Lint python
on:
  pull_request:
    paths:
      - 'app/**.py'
      - 'layer/**.py'

jobs:
  black-isort:
    name: Black & isort lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: '.'
      - name: Check import order using isort
        uses: isort/isort-action@v1
        id: action_isort
        with:
          configuration: '--profile=black'
      - name: Annotate diff changes using reviewdog
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: 'isort & black'
  flake8:
    runs-on: ubuntu-latest
    name: flake8 Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: flake8 Lint comment to PR
        uses: reviewdog/action-flake8@v3
        with:
          reporter: github-pr-review
          flake8_args: --config=setup.cfg
      - name: flake8 Lint comment to PR check
        uses: reviewdog/action-flake8@v3
        with:
          reporter: github-pr-check
          flake8_args: --config=setup.cfg
